import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo/icon1.svg?v=2" type="image/svg+xml" sizes="256x256" />
        <link rel="icon" href="/logo/icon1.png?v=2" type="image/png" sizes="256x256" />
        <link rel="icon" href="/logo/icon1.png?v=2" type="image/png" sizes="128x128" />
        <link rel="icon" href="/logo/icon1.png?v=2" type="image/png" sizes="64x64" />
        <link rel="icon" href="/favicon.ico?v=2" type="image/x-icon" />
        <script async src="https://platform.twitter.com/widgets.js" charSet="utf-8"></script>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}